spring:
  application:
    name: NotificationMs
  kafka:
    listener:
      poll-timeout: 7000
    bootstrap-servers: localhost:9092
    consumer:
      group-id: notification_group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: "*"
            type:
              mapping: "com.paypal.UserMs.dto.UserRegisteredEvent:com.paypal.NotificationMs.dto.UserRegisteredEvent,com.paypal.TransactionMs.dto.TransactionCompleteEvent:com.paypal.NotificationMs.dto.TransactionCompleteEvent"
server:
  port: 8084

logging:
  level:
    com.paypal.NotificationMs: DEBUG
    org.springframework.kafka: DEBUG